
// /* SIGN UP */
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";


/* LOGIN */
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";


// FORGOT PASSWORD
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";


// VERIFICATION_CODE
export const VERIFICATION_CODE = "VERIFICATION_CODE";


//  VALIDATE VERIFICATION  CODE
export const VALIDATE_VERIFICATION_CODE_REQUEST = "VALIDATE_VERIFICATION_CODE_REQUEST";
export const VALIDATE_VERIFICATION_CODE_SUCCESS = "VALIDATE_VERIFICATION_CODE_SUCCESS";
export const VALIDATE_VERIFICATION_CODE_FAILED = "VALIDATE_VERIFICATION_CODE_FAILED";


// RESET PASSWORD //CHANGE PASS
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

// /* LOG OUT */
export const LOGOUT = "LOGOUT";

// /* UNAUTHORIZED */
export const UNAUTHORIZED_USER = "UNAUTHORIZED_USER"

/* STORE DEVICE ID IN REDUX */
export const SAVE_DEVICE_ID = "SAVE_DEVICE_ID";

/* STORE TOKEN IN REDUX */
export const SAVE_TOKEN = "SAVE_TOKEN";