
// PICKUP LOCATIONS

// get PICKUP LOCATIONS
export const GET_PICKUP_LOCATIONS_REQUEST = "GET_PICKUP_LOCATIONS_REQUEST";
export const GET_PICKUP_LOCATIONS_SUCCESS = "GET_PICKUP_LOCATIONS_SUCCESS";
export const GET_PICKUP_LOCATIONS_FAILED = "GET_PICKUP_LOCATIONS_FAILED";



// ADD PRODUCT 
export const SET_ORDERED_PRODUCT_DETAILS = "SET_ORDERED_PRODUCT_DETAILS";
export const SET_ORDER_DATE = "SET_ORDER_DATE";
export const SET_DELIVERY_TYPE = "SET_DELIVERY_TYPE";
export const SET_LOCATION_DETAILS = "SET_LOCATION_DETAILS";
















// ORDERS


// Add-order

// get PICKUP LOCATIONS
export const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILED = "ADD_ORDER_FAILED";


// get my all orders 
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS";
export const GET_MY_ORDERS_REQUEST = "GET_MY_ORDERS_REQUEST";
export const GET_MY_ORDERS_FAILED = "GET_MY_ORDERS_FAILED";






