
// Clear state when component will unmount execute
export const ON_UNMOUNT_COMPONENT = "ON_UNMOUNT_COMPONENT"





// EXPLORE

// get explore products
export const GET_EXPLORE_PRODUCTS_REQUEST = "GET_EXPLORE_PRODUCTS_REQUEST";
export const GET_EXPLORE_PRODUCTS_SUCCESS = "GET_EXPLORE_PRODUCTS_SUCCESS";
export const GET_EXPLORE_PRODUCTS_FAILED = "GET_EXPLORE_PRODUCTS_FAILED";




// get explore product details
export const GET_EXPLORE_PRODUCT_DETAILS_REQUEST = "GET_EXPLORE_PRODUCT_DETAILS_REQUEST";
export const GET_EXPLORE_PRODUCT_DETAILS_SUCCESS = "GET_EXPLORE_PRODUCT_DETAILS_SUCCESS";
export const GET_EXPLORE_PRODUCT_DETAILS_FAILED = "GET_EXPLORE_PRODUCT_DETAILS_FAILED";






// FAVOURITE

// get FAVOURITE products
export const GET_FAVOURITE_PRODUCTS_REQUEST = "GET_FAVOURITE_PRODUCTS_REQUEST";
export const GET_FAVOURITE_PRODUCTS_SUCCESS = "GET_FAVOURITE_PRODUCTS_SUCCESS";
export const GET_FAVOURITE_PRODUCTS_FAILED = "GET_FAVOURITE_PRODUCTS_FAILED";


// add FAVOURITE products
export const ADD_FAVOURITE_PRODUCTS_REQUEST = "ADD_FAVOURITE_PRODUCTS_REQUEST";
export const ADD_FAVOURITE_PRODUCTS_SUCCESS = "ADD_FAVOURITE_PRODUCTS_SUCCESS";
export const ADD_FAVOURITE_PRODUCTS_FAILED = "ADD_FAVOURITE_PRODUCTS_FAILED";
