


// PROFILE

//Get Profile
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

// Update Profile
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";








// ALLERGIES

//Get ALL ALLERGIES
export const GET_ALLERGIES_REQUEST = "GET_ALLERGIES_REQUEST";
export const GET_ALLERGIES_SUCCESS = "GET_ALLERGIES_SUCCESS";
export const GET_ALLERGIES_FAILED = "GET_ALLERGIES_FAILED";

//update my allergies
export const UPDATE_MY_ALLERGIES_REQUEST = "UPDATE_MY_ALLERGIES_REQUEST";
export const UPDATE_MY_ALLERGIES_SUCCESS = "UPDATE_MY_ALLERGIES_SUCCESS";
export const UPDATE_MY_ALLERGIES_FAILED = "UPDATE_MY_ALLERGIES_FAILED";

//update my other allergies
export const UPDATE_MY_OTHER_ALLERGIES = "UPDATE_MY_OTHER_ALLERGIES";

// get my allergies
export const GET_MY_ALLERGIES_REQUEST = "GET_MY_ALLERGIES_REQUEST";
export const GET_MY_ALLERGIES_SUCCESS = "GET_MY_ALLERGIES_SUCCESS";
export const GET_MY_ALLERGIES_FAILED = "GET_MY_ALLERGIES_FAILED";






// RESTRICTIONS


//Get ALL restrictions
export const GET_RESTRICTIONS_REQUEST = "GET_RESTRICTIONS_REQUEST";
export const GET_RESTRICTIONS_SUCCESS = "GET_RESTRICTIONS_SUCCESS";
export const GET_RESTRICTIONS_FAILED = "GET_RESTRICTIONS_FAILED";

//update my restrictions
export const UPDATE_MY_RESTRICTIONS_REQUEST = "UPDATE_MY_RESTRICTIONS_REQUEST";
export const UPDATE_MY_RESTRICTIONS_SUCCESS = "UPDATE_MY_RESTRICTIONS_SUCCESS";
export const UPDATE_MY_RESTRICTIONS_FAILED = "UPDATE_MY_RESTRICTIONS_FAILED";

// update my other restricitons
export const UPDATE_MY_OTHER_RESTRICTIONS = "UPDATE_MY_OTHER_RESTRICTIONS"

// get my restrictions
export const GET_MY_RESTRICTIONS_REQUEST = "GET_MY_RESTRICTIONS_REQUEST";
export const GET_MY_RESTRICTIONS_SUCCESS = "GET_MY_RESTRICTIONS_SUCCESS";
export const GET_MY_RESTRICTIONS_FAILED = "GET_MY_RESTRICTIONS_FAILED";










// Fitnesss

export const GET_FITNESS_GOALS_REQUEST = "GET_FITNESS_GOALS_REQUEST";
export const GET_FITNESS_GOALS_SUCCESS = "GET_FITNESS_GOALS_SUCCESS"
export const GET_FITNESS_GOALS_FAILED = "GET_FITNESS_GOALS_FAILED"
export const TOGGLE_FITNESS_GOAL = "TOGGLE_FITNESS_GOAL"



// update my fitness goal
export const UPDATE_MY_FITNESS_GOAL = 'UPDATE_MY_FITNESS_GOAL'



// udpate fitness goal
export const UPDATE_FITNESS_GOALS_REQUEST = "UPDATE_FITNESS_GOALS_REQUEST";
export const UPDATE_FITNESS_GOALS_SUCCESS = "UPDATE_FITNESS_GOALS_SUCCESS"
export const UPDATE_FITNESS_GOALS_FAILED = "UPDATE_FITNESS_GOALS_FAILED"









// SETTINGS PAGE ROUTE

export const SET_ALLOW_NOTIFICATION = "SET_ALLOW_NOTIFICATION";
export const SET_CONFIRM_ORDER = "SET_CONFIRM_ORDER";
export const SET_CONFIRMATION_TYPE = "SET_CONFIRMATION_TYPE";









// DELIVERY



// ADD DELIVERY ADDRESS
export const ADD_DELIVERY_ADDRESS_REQUEST = "ADD_DELIVERY_ADDRESS_REQUEST";
export const ADD_DELIVERY_ADDRESS_SUCCESS = "ADD_DELIVERY_ADDRESS_SUCCESS";
export const ADD_DELIVERY_ADDRESS_FAILED = "ADD_DELIVERY_ADDRESS_FAILED";


// GET DELIVERY ADDRESS
export const GET_DELIVERY_ADDRESS_REQUEST = "GET_DELIVERY_ADDRESS_REQUEST";
export const GET_DELIVERY_ADDRESS_SUCCESS = "GET_DELIVERY_ADDRESS_SUCCESS";
export const GET_DELIVERY_ADDRESS_FAILED = "GET_DELIVERY_ADDRESS_FAILED";
export const TOGGLE_DELIVERY_ADDRESS = "TOGGLE_DELIVERY_ADDRESS";






// PAYMENT



// ADD PAYMENT METHODS
export const ADD_PAYMENT_METHOD_REQUEST = "ADD_PAYMENT_METHOD_REQUEST";
export const ADD_PAYMENT_METHOD_SUCCESS = "ADD_PAYMENT_METHOD_SUCCESS";
export const ADD_PAYMENT_METHOD_FAILED = "ADD_PAYMENT_METHOD_FAILED";


// GET PAYMENT METHODS
export const GET_PAYMENT_METHODS_REQUEST = "GET_PAYMENT_METHODS_REQUEST";
export const GET_PAYMENT_METHODS_SUCCESS = "GET_PAYMENT_METHODS_SUCCESS";
export const GET_PAYMENT_METHODS_FAILED = "GET_PAYMENT_METHODS_FAILED";


// SET DEFAULT PAYMENT METHOD
export const SET_DEFAULT_PAYMENT_METHOD_REQUEST = "SET_DEFAULT_PAYMENT_METHOD_REQUEST";
export const SET_DEFAULT_PAYMENT_METHOD_SUCCESS = "SET_DEFAULT_PAYMENT_METHOD_SUCCESS";
export const SET_DEFAULT_PAYMENT_METHOD_FAILED = "SET_DEFAULT_PAYMENT_METHOD_FAILED";








// Subscriptions


// GET Subscriptions
export const GET_SUBSCRIPTIONS_REQUEST = "GET_SUBSCRIPTIONS_REQUEST";
export const GET_SUBSCRIPTIONS_SUCCESS = "GET_SUBSCRIPTIONS_SUCCESS";
export const GET_SUBSCRIPTIONS_FAILED = "GET_SUBSCRIPTIONS_FAILED";



// update Subscriptions
export const UPDATE_SUBSCRIPTION_REQUEST = "UPDATE_SUBSCRIPTION_REQUEST";
export const UPDATE_SUBSCRIPTION_SUCCESS = "UPDATE_SUBSCRIPTION_SUCCESS";
export const UPDATE_SUBSCRIPTION_FAILED = " UPDATE_SUBSCRIPTION_FAILED";